In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor, ExtraTreesRegressor ,AdaBoostRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsRegressor
from xgboost import XGBRegressor

In [2]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input,Dense,BatchNormalization,Dropout

c:\Users\Amir sohail\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\export\tf2onnx_lib.py:8: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  if not hasattr(np, "object"):

In [3]:
df = pd.read_csv("synthetic_food_delivery_transactions.csv")
df.head()

,order_id,customer_id,customer_loyalty_tier,customer_acquisition_channel,customer_signup_date,restaurant_id,restaurant_cuisine,restaurant_city,restaurant_rating,restaurant_avg_prep_time,...,total_amount,discount_code,discount_type,discount_value,order_status,weather_temperature,weather_precipitation,is_weekend,is_holiday,event_flag
0,4002,925,Gold,social_media,2024-07-22,124,American,Los Angeles,3.6,23,...,25.42,PROMO-BFUZ,percentage,4.97,completed,2.9,25.6,True,True,NaN
1,4879,3163,Bronze,referral,2023-03-17,43,Chinese,Houston,4.8,32,...,22.70,NaN,NaN,0.00,completed,4.0,0.4,True,True,NaN
2,1124,4154,Bronze,referral,2023-01-14,188,American,San Antonio,3.4,11,...,27.74,NaN,NaN,0.00,completed,4.4,0.0,True,True,NaN
3,6764,4530,Bronze,email,2024-02-26,91,Mediterranean,New York,3.1,17,...,31.85,NaN,NaN,0.00,completed,9.9,0.0,True,True,NaN
4,9073,2570,Bronze,paid_ads,2024-08-25,84,Mediterranean,San Antonio,3.2,28,...,28.46,NaN,NaN,0.00,completed,7.0,16.1,True,True,NaN

In [4]:
df.columns

Index(['order_id', 'customer_id', 'customer_loyalty_tier',
       'customer_acquisition_channel', 'customer_signup_date', 'restaurant_id',
       'restaurant_cuisine', 'restaurant_city', 'restaurant_rating',
       'restaurant_avg_prep_time', 'menu_item_id', 'menu_item_name',
       'menu_item_category', 'item_price', 'quantity', 'order_timestamp',
       'delivery_timestamp', 'delivery_duration_actual',
       'delivery_duration_estimated', 'delivery_fee', 'tip', 'total_amount',
       'discount_code', 'discount_type', 'discount_value', 'order_status',
       'weather_temperature', 'weather_precipitation', 'is_weekend',
       'is_holiday', 'event_flag'],
      dtype='object')

In [5]:
df["delivery_duration_actual"]

0       59.0
1       57.0
2       41.0
3       50.0
4       69.0
        ...
9995    42.0
9996     NaN
9997    68.0
9998    68.0
9999    67.0
Name: delivery_duration_actual, Length: 10000, dtype: float64

In [6]:
df.shape

(10000, 31)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 31 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   order_id                      10000 non-null  int64
 1   customer_id                   10000 non-null  int64
 2   customer_loyalty_tier         10000 non-null  object
 3   customer_acquisition_channel  10000 non-null  object
 4   customer_signup_date          10000 non-null  object
 5   restaurant_id                 10000 non-null  int64
 6   restaurant_cuisine            10000 non-null  object
 7   restaurant_city               10000 non-null  object
 8   restaurant_rating             10000 non-null  float64
 9   restaurant_avg_prep_time      10000 non-null  int64
 10  menu_item_id                  10000 non-null  int64
 11  menu_item_name                10000 non-null  object
 12  menu_item_category            10000 non-null  object
 13  item_price                    10000 non-null  float64
 14  quantity                      10000 non-null  int64
 15  order_timestamp               10000 non-null  object
 16  delivery_timestamp            9225 non-null   object
 17  delivery_duration_actual      9225 non-null   float64
 18  delivery_duration_estimated   10000 non-null  int64
 19  delivery_fee                  10000 non-null  float64
 20  tip                           10000 non-null  float64
 21  total_amount                  10000 non-null  float64
 22  discount_code                 1950 non-null   object
 23  discount_type                 1950 non-null   object
 24  discount_value                10000 non-null  float64
 25  order_status                  10000 non-null  object
 26  weather_temperature           10000 non-null  float64
 27  weather_precipitation         10000 non-null  float64
 28  is_weekend                    10000 non-null  bool
 29  is_holiday                    10000 non-null  bool
 30  event_flag                    790 non-null    object
dtypes: bool(2), float64(9), int64(7), object(13)
memory usage: 2.2+ MB

In [8]:
col = ["restaurant_rating", "restaurant_avg_prep_time", "item_price", "quantity", "delivery_duration_estimated", "delivery_fee", "tip", "total_amount", "discount_value", "weather_temperature", "weather_precipitation","delivery_duration_actual","customer_loyalty_tier","customer_acquisition_channel","restaurant_cuisine","order_timestamp","restaurant_city","is_holiday","is_weekend"]

dro_col = df.drop(columns=col,axis=1).columns

df.drop(columns=dro_col,axis=1,inplace=True)

df.head()

,customer_loyalty_tier,customer_acquisition_channel,restaurant_cuisine,restaurant_city,restaurant_rating,restaurant_avg_prep_time,item_price,quantity,order_timestamp,delivery_duration_actual,delivery_duration_estimated,delivery_fee,tip,total_amount,discount_value,weather_temperature,weather_precipitation,is_weekend,is_holiday
0,Gold,social_media,American,Los Angeles,3.6,23,24.86,1,2023-01-01 00:10:17,59.0,48,3.48,2.05,25.42,4.97,2.9,25.6,True,True
1,Bronze,referral,Chinese,Houston,4.8,32,15.25,1,2023-01-01 00:29:15,57.0,54,5.24,2.21,22.70,0.00,4.0,0.4,True,True
2,Bronze,referral,American,San Antonio,3.4,11,18.50,1,2023-01-01 04:06:27,41.0,29,5.95,3.29,27.74,0.00,4.4,0.0,True,True
3,Bronze,email,Mediterranean,New York,3.1,17,24.51,1,2023-01-01 05:05:28,50.0,42,7.27,0.07,31.85,0.00,9.9,0.0,True,True
4,Bronze,paid_ads,Mediterranean,San Antonio,3.2,28,23.50,1,2023-01-01 08:46:51,69.0,52,4.06,0.90,28.46,0.00,7.0,16.1,True,True

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
# df["discount_type"].mode()

In [11]:
df["delivery_duration_actual"] = df["delivery_duration_actual"].fillna(df["delivery_duration_actual"].mean())
# df["discount_type"] = df["discount_type"].fillna("percentage")

In [12]:
df["order_timestamp"]

def houer(times):
    time = str(times)
    new_time = time[11:len(time)-6]
    return int(new_time)

df["order_timestamp"] = df["order_timestamp"].apply(houer)
df.head()

,customer_loyalty_tier,customer_acquisition_channel,restaurant_cuisine,restaurant_city,restaurant_rating,restaurant_avg_prep_time,item_price,quantity,order_timestamp,delivery_duration_actual,delivery_duration_estimated,delivery_fee,tip,total_amount,discount_value,weather_temperature,weather_precipitation,is_weekend,is_holiday
0,Gold,social_media,American,Los Angeles,3.6,23,24.86,1,0,59.0,48,3.48,2.05,25.42,4.97,2.9,25.6,True,True
1,Bronze,referral,Chinese,Houston,4.8,32,15.25,1,0,57.0,54,5.24,2.21,22.70,0.00,4.0,0.4,True,True
2,Bronze,referral,American,San Antonio,3.4,11,18.50,1,4,41.0,29,5.95,3.29,27.74,0.00,4.4,0.0,True,True
3,Bronze,email,Mediterranean,New York,3.1,17,24.51,1,5,50.0,42,7.27,0.07,31.85,0.00,9.9,0.0,True,True
4,Bronze,paid_ads,Mediterranean,San Antonio,3.2,28,23.50,1,8,69.0,52,4.06,0.90,28.46,0.00,7.0,16.1,True,True

In [13]:
df.head()

,customer_loyalty_tier,customer_acquisition_channel,restaurant_cuisine,restaurant_city,restaurant_rating,restaurant_avg_prep_time,item_price,quantity,order_timestamp,delivery_duration_actual,delivery_duration_estimated,delivery_fee,tip,total_amount,discount_value,weather_temperature,weather_precipitation,is_weekend,is_holiday
0,Gold,social_media,American,Los Angeles,3.6,23,24.86,1,0,59.0,48,3.48,2.05,25.42,4.97,2.9,25.6,True,True
1,Bronze,referral,Chinese,Houston,4.8,32,15.25,1,0,57.0,54,5.24,2.21,22.70,0.00,4.0,0.4,True,True
2,Bronze,referral,American,San Antonio,3.4,11,18.50,1,4,41.0,29,5.95,3.29,27.74,0.00,4.4,0.0,True,True
3,Bronze,email,Mediterranean,New York,3.1,17,24.51,1,5,50.0,42,7.27,0.07,31.85,0.00,9.9,0.0,True,True
4,Bronze,paid_ads,Mediterranean,San Antonio,3.2,28,23.50,1,8,69.0,52,4.06,0.90,28.46,0.00,7.0,16.1,True,True

In [14]:
bool_col = ["is_weekend","is_holiday"]

df[bool_col] = df[bool_col].astype(int)
df.head()

,customer_loyalty_tier,customer_acquisition_channel,restaurant_cuisine,restaurant_city,restaurant_rating,restaurant_avg_prep_time,item_price,quantity,order_timestamp,delivery_duration_actual,delivery_duration_estimated,delivery_fee,tip,total_amount,discount_value,weather_temperature,weather_precipitation,is_weekend,is_holiday
0,Gold,social_media,American,Los Angeles,3.6,23,24.86,1,0,59.0,48,3.48,2.05,25.42,4.97,2.9,25.6,1,1
1,Bronze,referral,Chinese,Houston,4.8,32,15.25,1,0,57.0,54,5.24,2.21,22.70,0.00,4.0,0.4,1,1
2,Bronze,referral,American,San Antonio,3.4,11,18.50,1,4,41.0,29,5.95,3.29,27.74,0.00,4.4,0.0,1,1
3,Bronze,email,Mediterranean,New York,3.1,17,24.51,1,5,50.0,42,7.27,0.07,31.85,0.00,9.9,0.0,1,1
4,Bronze,paid_ads,Mediterranean,San Antonio,3.2,28,23.50,1,8,69.0,52,4.06,0.90,28.46,0.00,7.0,16.1,1,1

In [15]:
print(df["customer_loyalty_tier"].unique())
print(df["customer_acquisition_channel"].unique())
print(df["restaurant_cuisine"].unique())
print(df["restaurant_city"].unique())

['Gold' 'Bronze' 'Silver']
['social_media' 'referral' 'email' 'paid_ads' 'organic']
['American' 'Chinese' 'Mediterranean' 'Fast Food' 'Indian' 'Italian'
 'Japanese' 'Mexican']
['Los Angeles' 'Houston' 'San Antonio' 'New York' 'San Diego' 'Chicago'
 'Phoenix' 'Philadelphia']

In [16]:
one_col = ["customer_loyalty_tier","customer_acquisition_channel","restaurant_cuisine","restaurant_city"]

df = pd.get_dummies(df,columns=one_col,drop_first=True,dtype=int)
df.head()

,restaurant_rating,restaurant_avg_prep_time,item_price,quantity,order_timestamp,delivery_duration_actual,delivery_duration_estimated,delivery_fee,tip,total_amount,...,restaurant_cuisine_Japanese,restaurant_cuisine_Mediterranean,restaurant_cuisine_Mexican,restaurant_city_Houston,restaurant_city_Los Angeles,restaurant_city_New York,restaurant_city_Philadelphia,restaurant_city_Phoenix,restaurant_city_San Antonio,restaurant_city_San Diego
0,3.6,23,24.86,1,0,59.0,48,3.48,2.05,25.42,...,0,0,0,0,1,0,0,0,0,0
1,4.8,32,15.25,1,0,57.0,54,5.24,2.21,22.70,...,0,0,0,1,0,0,0,0,0,0
2,3.4,11,18.50,1,4,41.0,29,5.95,3.29,27.74,...,0,0,0,0,0,0,0,0,1,0
3,3.1,17,24.51,1,5,50.0,42,7.27,0.07,31.85,...,0,1,0,0,0,1,0,0,0,0
4,3.2,28,23.50,1,8,69.0,52,4.06,0.90,28.46,...,0,1,0,0,0,0,0,0,1,0

In [17]:
scaler_col = ["restaurant_rating", "restaurant_avg_prep_time", "item_price", "quantity", "delivery_duration_estimated", "delivery_fee", "tip", "total_amount", "discount_value", "weather_temperature", "weather_precipitation","order_timestamp"]

scaler = StandardScaler()
df[scaler_col] = scaler.fit_transform(df[scaler_col])
df.head()

,restaurant_rating,restaurant_avg_prep_time,item_price,quantity,order_timestamp,delivery_duration_actual,delivery_duration_estimated,delivery_fee,tip,total_amount,...,restaurant_cuisine_Japanese,restaurant_cuisine_Mediterranean,restaurant_cuisine_Mexican,restaurant_city_Houston,restaurant_city_Los Angeles,restaurant_city_New York,restaurant_city_Philadelphia,restaurant_city_Phoenix,restaurant_city_San Antonio,restaurant_city_San Diego
0,-0.701994,0.101703,0.555208,-0.512142,-1.640487,59.0,0.673445,-0.888848,-0.398601,-0.437108,...,0,0,0,0,1,0,0,0,0,0
1,1.348471,1.370520,-0.574125,-0.512142,-1.640487,57.0,1.325408,0.127059,-0.353313,-0.557622,...,0,0,0,1,0,0,0,0,0,0
2,-1.043738,-1.590053,-0.192197,-0.512142,-1.064539,41.0,-1.391104,0.536885,-0.047625,-0.334317,...,0,0,0,0,0,0,0,0,1,0
3,-1.556354,-0.744175,0.514077,-0.512142,-0.920552,50.0,0.021482,1.298815,-0.959029,-0.152217,...,0,1,0,0,0,1,0,0,0,0
4,-1.385482,0.806601,0.395385,-0.512142,-0.488591,69.0,1.108087,-0.554060,-0.724102,-0.302416,...,0,1,0,0,0,0,0,0,1,0

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 35 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   restaurant_rating                          10000 non-null  float64
 1   restaurant_avg_prep_time                   10000 non-null  float64
 2   item_price                                 10000 non-null  float64
 3   quantity                                   10000 non-null  float64
 4   order_timestamp                            10000 non-null  float64
 5   delivery_duration_actual                   10000 non-null  float64
 6   delivery_duration_estimated                10000 non-null  float64
 7   delivery_fee                               10000 non-null  float64
 8   tip                                        10000 non-null  float64
 9   total_amount                               10000 non-null  float64
 10  discount_value                             10000 non-null  float64
 11  weather_temperature                        10000 non-null  float64
 12  weather_precipitation                      10000 non-null  float64
 13  is_weekend                                 10000 non-null  int64
 14  is_holiday                                 10000 non-null  int64
 15  customer_loyalty_tier_Gold                 10000 non-null  int64
 16  customer_loyalty_tier_Silver               10000 non-null  int64
 17  customer_acquisition_channel_organic       10000 non-null  int64
 18  customer_acquisition_channel_paid_ads      10000 non-null  int64
 19  customer_acquisition_channel_referral      10000 non-null  int64
 20  customer_acquisition_channel_social_media  10000 non-null  int64
 21  restaurant_cuisine_Chinese                 10000 non-null  int64
 22  restaurant_cuisine_Fast Food               10000 non-null  int64
 23  restaurant_cuisine_Indian                  10000 non-null  int64
 24  restaurant_cuisine_Italian                 10000 non-null  int64
 25  restaurant_cuisine_Japanese                10000 non-null  int64
 26  restaurant_cuisine_Mediterranean           10000 non-null  int64
 27  restaurant_cuisine_Mexican                 10000 non-null  int64
 28  restaurant_city_Houston                    10000 non-null  int64
 29  restaurant_city_Los Angeles                10000 non-null  int64
 30  restaurant_city_New York                   10000 non-null  int64
 31  restaurant_city_Philadelphia               10000 non-null  int64
 32  restaurant_city_Phoenix                    10000 non-null  int64
 33  restaurant_city_San Antonio                10000 non-null  int64
 34  restaurant_city_San Diego                  10000 non-null  int64
dtypes: float64(13), int64(22)
memory usage: 2.7 MB

In [19]:
X = df.drop("delivery_duration_actual",axis=1)
y = df["delivery_duration_actual"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [20]:
X.columns

Index(['restaurant_rating', 'restaurant_avg_prep_time', 'item_price',
       'quantity', 'order_timestamp', 'delivery_duration_estimated',
       'delivery_fee', 'tip', 'total_amount', 'discount_value',
       'weather_temperature', 'weather_precipitation', 'is_weekend',
       'is_holiday', 'customer_loyalty_tier_Gold',
       'customer_loyalty_tier_Silver', 'customer_acquisition_channel_organic',
       'customer_acquisition_channel_paid_ads',
       'customer_acquisition_channel_referral',
       'customer_acquisition_channel_social_media',
       'restaurant_cuisine_Chinese', 'restaurant_cuisine_Fast Food',
       'restaurant_cuisine_Indian', 'restaurant_cuisine_Italian',
       'restaurant_cuisine_Japanese', 'restaurant_cuisine_Mediterranean',
       'restaurant_cuisine_Mexican', 'restaurant_city_Houston',
       'restaurant_city_Los Angeles', 'restaurant_city_New York',
       'restaurant_city_Philadelphia', 'restaurant_city_Phoenix',
       'restaurant_city_San Antonio', 'restaurant_city_San Diego'],
      dtype='object')

In [21]:
model_ann = Sequential([
    Input(shape=(X.shape[1],)),
    Dense(128,activation="relu"),
    BatchNormalization(),
    Dropout(0.3),
    Dense(64,activation="relu"),
    BatchNormalization(),
    Dropout(0.2),
    Dense(32,activation="relu"),
    BatchNormalization(),
    Dropout(0.1),
    Dense(16,activation="relu"),
    BatchNormalization(),
    Dense(8,activation="relu"),
    Dense(1)
])

In [22]:
model_ann.compile(optimizer="adam",loss="mse",metrics=["r2_score"])

In [23]:
his = model_ann.fit(
    X_train,y_train,
    validation_data = (X_test,y_test),
    epochs = 100,batch_size = 16,
    verbose = 1
)

Epoch 1/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 1303.4520 - r2_score: -9.4457 - val_loss: 178.8869 - val_r2_score: -0.4336
Epoch 2/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 125.2005 - r2_score: -0.0034 - val_loss: 59.6478 - val_r2_score: 0.5220
Epoch 3/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 77.6261 - r2_score: 0.3779 - val_loss: 57.7979 - val_r2_score: 0.5368
Epoch 4/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 69.7484 - r2_score: 0.4411 - val_loss: 53.2084 - val_r2_score: 0.5736
Epoch 5/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 65.5802 - r2_score: 0.4744 - val_loss: 48.3963 - val_r2_score: 0.6122
Epoch 6/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 65.0277 - r2_score: 0.4789 - val_loss: 49.1777 - val_r2_score: 0.6059
Epoch 7/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 61.1545 - r2_score: 0.5099 - val_loss: 51.9107 - val_r2_score: 0.5840
Epoch 8/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 58.9984 - r2_score: 0.5272 - val_loss: 55.2815 - val_r2_score: 0.5570
Epoch 9/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 58.3011 - r2_score: 0.5328 - val_loss: 63.3634 - val_r2_score: 0.4922
Epoch 10/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 58.5004 - r2_score: 0.5312 - val_loss: 54.0494 - val_r2_score: 0.5669
Epoch 11/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 56.9208 - r2_score: 0.5438 - val_loss: 49.4314 - val_r2_score: 0.6039
Epoch 12/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 56.2793 - r2_score: 0.5490 - val_loss: 55.3965 - val_r2_score: 0.5561
Epoch 13/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 55.3859 - r2_score: 0.5561 - val_loss: 50.2304 - val_r2_score: 0.5975
Epoch 14/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 54.6144 - r2_score: 0.5623 - val_loss: 48.9734 - val_r2_score: 0.6075
Epoch 15/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 53.5713 - r2_score: 0.5707 - val_loss: 47.9815 - val_r2_score: 0.6155
Epoch 16/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 54.0342 - r2_score: 0.5670 - val_loss: 52.9029 - val_r2_score: 0.5761
Epoch 17/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 53.3691 - r2_score: 0.5723 - val_loss: 47.0957 - val_r2_score: 0.6226
Epoch 18/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 54.0467 - r2_score: 0.5669 - val_loss: 50.8396 - val_r2_score: 0.5926
Epoch 19/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 53.8286 - r2_score: 0.5686 - val_loss: 50.7142 - val_r2_score: 0.5936
Epoch 20/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 52.6173 - r2_score: 0.5783 - val_loss: 51.6576 - val_r2_score: 0.5860
Epoch 21/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 53.5861 - r2_score: 0.5706 - val_loss: 57.9800 - val_r2_score: 0.5354
Epoch 22/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 52.9518 - r2_score: 0.5757 - val_loss: 55.2070 - val_r2_score: 0.5576
Epoch 23/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 52.4162 - r2_score: 0.5799 - val_loss: 62.6988 - val_r2_score: 0.4975
Epoch 24/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 51.8090 - r2_score: 0.5848 - val_loss: 46.7041 - val_r2_score: 0.6257
Epoch 25/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 52.2186 - r2_score: 0.5815 - val_loss: 45.9969 - val_r2_score: 0.6314
Epoch 26/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 50.8630 - r2_score: 0.5924 - val_loss: 45.7981 - val_r2_score: 0.6330
Epoch 27/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 51.5349 - r2_score: 0.5870 - val_loss: 44.1107 - val_r2_score: 0.6465
Epoch 28/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 51.2963 - r2_score: 0.5889 - val_loss: 46.7472 - val_r2_score: 0.6254
Epoch 29/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 51.3156 - r2_score: 0.5888 - val_loss: 43.2643 - val_r2_score: 0.6533
Epoch 30/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 50.4883 - r2_score: 0.5954 - val_loss: 43.8803 - val_r2_score: 0.6484
Epoch 31/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 50.2416 - r2_score: 0.5974 - val_loss: 44.9018 - val_r2_score: 0.6402
Epoch 32/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 50.7449 - r2_score: 0.5933 - val_loss: 44.1356 - val_r2_score: 0.6463
Epoch 33/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 50.1554 - r2_score: 0.5981 - val_loss: 44.5369 - val_r2_score: 0.6431
Epoch 34/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 50.7161 - r2_score: 0.5936 - val_loss: 44.3036 - val_r2_score: 0.6450
Epoch 35/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 49.9853 - r2_score: 0.5994 - val_loss: 42.6435 - val_r2_score: 0.6583
Epoch 36/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 48.9746 - r2_score: 0.6075 - val_loss: 43.1750 - val_r2_score: 0.6540
Epoch 37/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 49.8072 - r2_score: 0.6009 - val_loss: 42.3598 - val_r2_score: 0.6605
Epoch 38/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 49.0776 - r2_score: 0.6067 - val_loss: 42.4175 - val_r2_score: 0.6601
Epoch 39/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 49.8832 - r2_score: 0.6002 - val_loss: 42.5734 - val_r2_score: 0.6588
Epoch 40/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 49.4611 - r2_score: 0.6036 - val_loss: 43.0743 - val_r2_score: 0.6548
Epoch 41/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 49.0172 - r2_score: 0.6072 - val_loss: 44.5918 - val_r2_score: 0.6427
Epoch 42/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 47.9632 - r2_score: 0.6156 - val_loss: 43.6661 - val_r2_score: 0.6501
Epoch 43/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 48.9645 - r2_score: 0.6076 - val_loss: 43.6290 - val_r2_score: 0.6504
Epoch 44/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 49.1157 - r2_score: 0.6064 - val_loss: 42.7644 - val_r2_score: 0.6573
Epoch 45/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 48.0280 - r2_score: 0.6151 - val_loss: 42.6618 - val_r2_score: 0.6581
Epoch 46/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 48.1300 - r2_score: 0.6143 - val_loss: 45.1932 - val_r2_score: 0.6378
Epoch 47/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 47.3077 - r2_score: 0.6209 - val_loss: 43.3711 - val_r2_score: 0.6524
Epoch 48/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 47.7082 - r2_score: 0.6177 - val_loss: 43.6862 - val_r2_score: 0.6499
Epoch 49/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 46.6463 - r2_score: 0.6262 - val_loss: 43.2274 - val_r2_score: 0.6536
Epoch 50/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 47.2187 - r2_score: 0.6216 - val_loss: 44.2258 - val_r2_score: 0.6456
Epoch 51/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 48.5849 - r2_score: 0.6106 - val_loss: 45.0398 - val_r2_score: 0.6391
Epoch 52/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 46.2473 - r2_score: 0.6294 - val_loss: 44.1771 - val_r2_score: 0.6460
Epoch 53/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 47.7439 - r2_score: 0.6174 - val_loss: 44.1316 - val_r2_score: 0.6463
Epoch 54/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 47.7268 - r2_score: 0.6175 - val_loss: 43.5834 - val_r2_score: 0.6507
Epoch 55/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 46.2679 - r2_score: 0.6292 - val_loss: 45.5583 - val_r2_score: 0.6349
Epoch 56/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 45.9843 - r2_score: 0.6315 - val_loss: 44.7526 - val_r2_score: 0.6414
Epoch 57/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 47.0718 - r2_score: 0.6228 - val_loss: 44.5104 - val_r2_score: 0.6433
Epoch 58/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 45.5582 - r2_score: 0.6349 - val_loss: 43.7104 - val_r2_score: 0.6497
Epoch 59/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 46.4212 - r2_score: 0.6280 - val_loss: 43.2769 - val_r2_score: 0.6532
Epoch 60/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 46.2174 - r2_score: 0.6296 - val_loss: 43.2278 - val_r2_score: 0.6536
Epoch 61/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 45.6623 - r2_score: 0.6341 - val_loss: 43.7863 - val_r2_score: 0.6491
Epoch 62/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 45.9441 - r2_score: 0.6318 - val_loss: 44.7463 - val_r2_score: 0.6414
Epoch 63/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 46.2984 - r2_score: 0.6290 - val_loss: 42.4587 - val_r2_score: 0.6597
Epoch 64/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 45.8219 - r2_score: 0.6328 - val_loss: 42.9316 - val_r2_score: 0.6560
Epoch 65/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 46.1923 - r2_score: 0.6298 - val_loss: 42.8099 - val_r2_score: 0.6569
Epoch 66/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 45.3542 - r2_score: 0.6365 - val_loss: 43.2771 - val_r2_score: 0.6532
Epoch 67/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 44.4871 - r2_score: 0.6435 - val_loss: 43.2185 - val_r2_score: 0.6537
Epoch 68/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 44.8270 - r2_score: 0.6408 - val_loss: 42.7704 - val_r2_score: 0.6572
Epoch 69/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 43.8387 - r2_score: 0.6487 - val_loss: 42.7347 - val_r2_score: 0.6575
Epoch 70/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 45.6779 - r2_score: 0.6339 - val_loss: 43.9089 - val_r2_score: 0.6481
Epoch 71/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 44.0116 - r2_score: 0.6473 - val_loss: 44.0682 - val_r2_score: 0.6468
Epoch 72/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 44.6263 - r2_score: 0.6424 - val_loss: 43.4872 - val_r2_score: 0.6515
Epoch 73/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 43.9685 - r2_score: 0.6476 - val_loss: 43.7064 - val_r2_score: 0.6497
Epoch 74/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 44.0253 - r2_score: 0.6472 - val_loss: 43.3986 - val_r2_score: 0.6522
Epoch 75/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 44.2483 - r2_score: 0.6454 - val_loss: 43.6957 - val_r2_score: 0.6498
Epoch 76/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 43.6702 - r2_score: 0.6500 - val_loss: 43.8180 - val_r2_score: 0.6489
Epoch 77/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 43.7819 - r2_score: 0.6491 - val_loss: 43.6621 - val_r2_score: 0.6501
Epoch 78/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 43.4185 - r2_score: 0.6521 - val_loss: 43.7230 - val_r2_score: 0.6496
Epoch 79/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 43.4814 - r2_score: 0.6515 - val_loss: 43.5587 - val_r2_score: 0.6509
Epoch 80/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 43.4572 - r2_score: 0.6517 - val_loss: 44.1537 - val_r2_score: 0.6462
Epoch 81/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 43.3804 - r2_score: 0.6524 - val_loss: 43.9391 - val_r2_score: 0.6479
Epoch 82/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 42.7514 - r2_score: 0.6574 - val_loss: 43.1629 - val_r2_score: 0.6541
Epoch 83/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 43.1614 - r2_score: 0.6541 - val_loss: 43.6623 - val_r2_score: 0.6501
Epoch 84/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 42.6406 - r2_score: 0.6583 - val_loss: 44.5737 - val_r2_score: 0.6428
Epoch 85/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 43.6823 - r2_score: 0.6499 - val_loss: 44.0245 - val_r2_score: 0.6472
Epoch 86/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 42.6326 - r2_score: 0.6583 - val_loss: 44.0160 - val_r2_score: 0.6473
Epoch 87/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 42.9925 - r2_score: 0.6555 - val_loss: 43.2948 - val_r2_score: 0.6530
Epoch 88/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 42.8230 - r2_score: 0.6568 - val_loss: 42.9236 - val_r2_score: 0.6560
Epoch 89/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 42.5091 - r2_score: 0.6593 - val_loss: 43.9639 - val_r2_score: 0.6477
Epoch 90/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 42.6261 - r2_score: 0.6584 - val_loss: 43.5368 - val_r2_score: 0.6511
Epoch 91/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 42.3335 - r2_score: 0.6607 - val_loss: 43.3837 - val_r2_score: 0.6523
Epoch 92/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 42.1036 - r2_score: 0.6626 - val_loss: 43.3226 - val_r2_score: 0.6528
Epoch 93/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 42.9335 - r2_score: 0.6559 - val_loss: 44.7025 - val_r2_score: 0.6418
Epoch 94/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 41.8736 - r2_score: 0.6644 - val_loss: 43.8978 - val_r2_score: 0.6482
Epoch 95/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 41.6976 - r2_score: 0.6658 - val_loss: 44.1193 - val_r2_score: 0.6464
Epoch 96/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 41.7605 - r2_score: 0.6653 - val_loss: 43.2631 - val_r2_score: 0.6533
Epoch 97/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 41.5971 - r2_score: 0.6666 - val_loss: 43.6179 - val_r2_score: 0.6505
Epoch 98/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 41.6711 - r2_score: 0.6661 - val_loss: 43.8128 - val_r2_score: 0.6489
Epoch 99/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 42.1340 - r2_score: 0.6623 - val_loss: 44.0633 - val_r2_score: 0.6469
Epoch 100/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 41.6278 - r2_score: 0.6664 - val_loss: 44.6070 - val_r2_score: 0.6425

In [24]:
model_ann.evaluate(
    # X_train,y_train,
    X_test,y_test,
    verbose = 1
)

63/63 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 44.6070 - r2_score: 0.6425

[44.6070442199707, 0.6425280570983887]

In [25]:
results = []
models = {
    'Linear Regression': LinearRegression(),
    'Ridge Regression': Ridge(alpha=1.0),
    'Lasso Regression': Lasso(alpha=0.1, max_iter=10000),
    'ElasticNet': ElasticNet(alpha=0.1, l1_ratio=0.5),
    'Decision Tree': DecisionTreeRegressor(random_state=42),
    'Random Forest': RandomForestRegressor(random_state=42, n_jobs=-1),
    'Extra Trees': ExtraTreesRegressor(random_state=42, n_jobs=-1),
    'Gradient Boosting': GradientBoostingRegressor(random_state=42),
    'K-Neighbors': KNeighborsRegressor(),
    'Support Vector Regressor': SVR(kernel='rbf'),
    "XGBoost": XGBRegressor(random_state=42),
    "AdaBoost": AdaBoostRegressor(random_state=42),
}

In [26]:
for name,model in models.items():
    model.fit(X_train,y_train)
    y_pred = model.predict(X_test)
    R2_score = r2_score(y_test,y_pred)
    MSE = mean_squared_error(y_test, y_pred)
    MAE = mean_absolute_error(y_test, y_pred)
    RMSE = np.sqrt(MSE)
    results.append({
        "Name":name,
        "R2_score":R2_score,
        "MSE":MSE,
        "MAE":MAE,
        "RMSE":RMSE
    })

results_df = pd.DataFrame(results)
results_df

                        Name  R2_score        MSE       MAE      RMSE
0          Linear Regression  0.625375  46.748309  5.658460  6.837273
1           Ridge Regression  0.625385  46.747135  5.658391  6.837188
2           Lasso Regression  0.626842  46.565241  5.647578  6.823873
3                 ElasticNet  0.626406  46.619720  5.652129  6.827864
4              Decision Tree  0.337445  82.678275  7.282976  9.092759
5              Random Forest  0.666328  41.637900  5.369307  6.452744
6                Extra Trees  0.648906  43.812016  5.482445  6.619065
7          Gradient Boosting  0.678386  40.133207  5.302212  6.335078
8                K-Neighbors  0.492174  63.370130  6.429585  7.960536
9   Support Vector Regressor  0.625386  46.746913  5.650198  6.837171
10                   XGBoost  0.631738  45.954262  5.578056  6.778957
11                  AdaBoost  0.673627  40.727055  5.347694  6.381775

In [27]:
model_final = models["AdaBoost"]
y_pred = model.predict(X_test)
r2_score(y_test,y_pred)

0.6736274948023422

In [28]:
from joblib import dump

dump(model_final, 'model.pkl')
dump(scaler, 'scaler.pkl')
dump(X.columns.tolist(), 'columns.pkl')

['columns.pkl']